### PR TITLE
lorenPicture

### PR DESCRIPTION
**Pull request by LorenK777**

### CODE REVIEW

**Comment by LorenK777** [comment]
- What? Uploaded image for Cohort4 image.
- Why? The image was provided by team leader and follows the image protocol. 
- How? Uploaded locally and committed branch.
- Testing? Reviewed image in VS Code live server and it is the correct image. No further testing at this moment.
- Screenshots (optional) See attached images
- Anything Else? Nothing at this time.

**Review by J0NUll — COMMENTED** [review]
Photo was not formatted as a square.

**Comment by Wom2** [comment]
They want you to make the picture a square. Andrew found a random third party picture editing website (. https://squareanimage.com/ )select the square crop option and use the resulting image instead of the one Richard made.

**Comment by UnCoqui** [comment]
Old pull request

**Pull request closed without merging**
