### PR TITLE
Diego picture2

### PR DESCRIPTION
**Pull request by Tazmaniego**
What? Uploaded image for Cohort 1 and updated new information for Cohort 1 card.
Why? The image was provided by team leader and follows the image protocol.
How? Uploaded locally and committed branch.
Testing? I reviewed the image in VS Code Live Server and it is the correct image and information on Cohort card 1. No further testing at this moment.
Anything else? Nothing at this time.
image

### CODE REVIEW

**Review by JDiggs1990 — CHANGES_REQUESTED** [review]
Screenshot of final card on the website is requested. Use Command+Shift+4
That was the only alteration needed I observed. May want to delete Cohort1.png.jpg from directory but likely unnecessary. Image may need to be squared, unclear to me.

**Review by UnCoqui — COMMENTED** [review]
You can square the image using the following website:

https://squareanimage.com/

**Comment by Tazmaniego** [comment]
Changes? I have been requested to resize my Cohort image and did it by modifying it on a website.

**Comment by UnCoqui** [comment]
Picture looks good. A screenshot helps in seeing the final version for review.

**Comment by Tazmaniego** [comment]
image

**Review by JDiggs1990 — APPROVED** [review]
Changes look good, sorry for missing the update, second review request. 
Screenshot of final product added and image squared.

**Pull request merged**
